In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/SHAKSHAM/Desktop/jupyter/at1.csv")
# print(df)
date=input("Enter date- dd/mm/yyyy")
df[date]='A'  #add new date column
# print(df)
df.to_csv("C:/Users/SHAKSHAM/Desktop/jupyter/at1.csv",index=False)
df

Enter date- dd/mm/yyyy03/06/2000

,01-07-2019,02-07-2019,03-07-2019,04-07-2019,15-04-2020,16-07-2020,20-06-2020,Id,Name,Unnamed: 8,...,10-07-2001,24/11/2002,24/10/2001,2020-07-19,19/07/2020,07/09/2020,25/09/2020,31/05/2021,31/07/2000,03/06/2000
0,A,A,A,P,A,A,A,12,gaurav,A,...,A,A,A,A,A,A,A,A,A,A
1,P,P,A,P,A,A,A,123,Bhavnath,A,...,A,A,A,A,A,A,A,A,A,A
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,457,jojo,NaN,...,A,A,A,A,A,A,A,A,A,A
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,345,shikhar,NaN,...,A,A,A,A,A,A,A,A,A,A
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134,rajat goyal,NaN,...,A,A,A,A,A,A,A,A,A,A
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156,rajesh,NaN,...,A,A,P,A,A,A,A,A,A,A
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154,yogesh,NaN,...,P,A,A,A,A,A,A,A,A,A
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156,seema,NaN,...,NaN,NaN,P,A,A,A,A,A,A,A
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165,ankush goyal,NaN,...,NaN,NaN,NaN,NaN,P,A,A,A,A,A
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,234,janiy vedant,NaN,...,NaN,NaN,NaN,NaN,NaN,P,P,A,A,A
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,213,jainy vedant,NaN,...,NaN,NaN,NaN,NaN,NaN,P,A,A,A,A
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,234,dfghhgfd,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,P,A,A,A
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23567890,SAKSHAM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,A,A
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2345678,SAKSHAM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,A
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186,ptanhi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,A

In [10]:
import pandas as pd
df=pd.read_csv("C:/Users/SHAKSHAM/Desktop/jupyter/at1.csv")
import cv2
cam = cv2.VideoCapture(0)
detector = cv2.CascadeClassifier('C:/Users/SHAKSHAM/Desktop/jupyter/haarcascades/haarcascade_frontalface_default.xml')

Id = input('Enter your id:')
Name=input('Enter your name:')
df2 = pd.DataFrame({"Id":[Id],"Name":[Name]})
df=pd.concat([df,df2]).drop_duplicates().reset_index(drop=True)
df.to_csv("C:/Users/SHAKSHAM/Desktop/jupyter/at1.csv",index=False)
sampleNum = 0
while (True):
    ret, img = cam.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGRA2GRAY)
    faces = detector.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x + w, y + h), (144, 1, 1), 3)

        # incrementing sample number
        sampleNum = sampleNum + 1
        # saving the captured face in the dataset folder
        cv2.imwrite(
            "C:/Users/SHAKSHAM/Desktop/jupyter/face/user." + Id + '.' + str(sampleNum) + ".jpg",
            gray[y:y + h, x:x+w])

        cv2.imshow('frame', img)
    # wait for 100 miliseconds
    if cv2.waitKey(100) & 0xFF == ord('q'):
        break
    # break if the sample number is morethan 20
    elif sampleNum > 20:
        break
cam.release()
cv2.destroyAllWindows()

Enter your id:186
Enter your name:ptanhi

In [3]:
#train data
import os
import cv2
import numpy as np
from PIL import Image

print(cv2.face)
# recognizer=cv2.face.LBPHFaceRecognizer_create()
# recognizer = cv2.face.LBPHFaceRecognizer_create()
# path='C:/Users/SHAKSHAM/Desktop/jupyter/face'

# def getImagesWithID(path):
#     imagePaths=[os.path.join(path,f) for f in os.listdir(path)]
#     faces=[]
#     IDs=[]
#     for imagePath in imagePaths:
#         faceImg=Image.open(imagePath).convert('L')
#         faceNp=np.array(faceImg,'uint8')
#         ID=int(os.path.split(imagePath)[-1].split('.')[1])
#         faces.append(faceNp)
#         IDs.append(ID)
#         cv2.imshow("training",faceNp)
#         cv2.waitKey(100) # for 10 milliseconds wait......
#     return np.array(IDs), faces

# Ids, faces=getImagesWithID(path)
# recognizer.train(faces,np.array(Ids))
# recognizer.save('C:/Users/SHAKSHAM/Desktop/jupyter/trainningData.yml')
# cv2.destroyAllWindows()

<module 'cv2.face'>

In [5]:
import cv2
import numpy as np
import pandas as pd
date=input("Enter date- dd/mm/yyyy")
faceDetect = cv2.CascadeClassifier("C:/Users/SHAKSHAM/Desktop/jupyter/haarcascades/haarcascade_frontalface_default.xml")
cam = cv2.VideoCapture(0)
rec = cv2.face.LBPHFaceRecognizer_create()
rec.read("C:/Users/SHAKSHAM/Desktop/jupyter/trainningData.yml")
id = 0
font = cv2.FONT_HERSHEY_COMPLEX_SMALL

df=pd.read_csv("C:/Users/SHAKSHAM/Desktop/jupyter/at1.csv")

while (True):

    ret, img = cam.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGRA2GRAY)
    faces = faceDetect.detectMultiScale(gray, 2, 4)
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), 2)
        id, conf = rec.predict(gray[y:y + h, x:x+w])
        id1 = df['Name'][df.Id==id]
        df[date][df.Id==id]='P'
        df.to_csv("C:/Users/SHAKSHAM/Desktop/jupyter/at1.csv",index=False)
        cv2.putText(img, str(id1), (x, y + h), font, 3, 255)
    cv2.imshow("Face", img)
    if (cv2.waitKey(1) & 0xFF == ord('q')):
        break

cam.release()
cv2.destroyAllWindows()

Enter date- dd/mm/yyyy31/07/2000

<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'
<ipython-input-5-09435fab6ad7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date][df.Id==id]='P'